local Players=game:GetService("Players")
local TweenService=game:GetService("TweenService")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local Config=require(ReplicatedStorage:WaitForChild("Config"))
local Minions={Active=false,Folder=nil,Arena=nil,_token=0}
local floors={22,40,58,76,94}
local palettes={{Color3.fromRGB(70,115,170),Color3.fromRGB(40,45,55)},{Color3.fromRGB(75,145,105),Color3.fromRGB(45,55,50)},{Color3.fromRGB(175,120,70),Color3.fromRGB(55,48,42)},{Color3.fromRGB(125,90,155),Color3.fromRGB(45,40,52)},{Color3.fromRGB(190,150,55),Color3.fromRGB(55,50,40)}}
local function piece(m,n,s,cf,c,mat)local p=Instance.new("Part");p.Name=n;p.Size=s;p.CFrame=cf;p.Anchored=true;p.CanCollide=false;p.CanTouch=false;p.CanQuery=true;p.Color=c;p.Material=mat or Enum.Material.SmoothPlastic;p.Parent=m;return p end
local function fb(player,k,t)local r=ReplicatedStorage:FindFirstChild("Remotes");local f=r and r:FindFirstChild("Feedback");if f then f:FireClient(player,k,t)end end
local function make(parent,name,pos,floor,index)local c=palettes[floor];local m=Instance.new("Model");m.Name=name;m.Parent=parent;local root=piece(m,"Root",Vector3.new(2,2,1),CFrame.new(pos),Color3.new(1,1,1));root.Transparency=1;piece(m,"Body",Vector3.new(3.2,3.8,1.8),CFrame.new(pos+Vector3.new(0,3.2,0)),c[1]);local head=piece(m,"Head",Vector3.new(2.5,2.5,2.5),CFrame.new(pos+Vector3.new(0,6.05,0)),c[1]);piece(m,"Hood",Vector3.new(2.7,.7,2.7),CFrame.new(pos+Vector3.new(0,7.35,0)),c[2]);piece(m,"ArmL",Vector3.new(.9,3.3,.9),CFrame.new(pos+Vector3.new(-2,3.2,0)),c[2]);piece(m,"ArmR",Vector3.new(.9,3.3,.9),CFrame.new(pos+Vector3.new(2,3.2,0)),c[2]);piece(m,"LegL",Vector3.new(1.15,3,1.15),CFrame.new(pos+Vector3.new(-.75,.65,0)),c[2]);piece(m,"LegR",Vector3.new(1.15,3,1.15),CFrame.new(pos+Vector3.new(.75,.65,0)),c[2]);piece(m,"EyeL",Vector3.new(.3,.3,.12),CFrame.new(pos+Vector3.new(-.45,6.15,-1.22)),Color3.fromRGB(255,220,120),Enum.Material.Neon);piece(m,"EyeR",Vector3.new(.3,.3,.12),CFrame.new(pos+Vector3.new(.45,6.15,-1.22)),Color3.fromRGB(255,220,120),Enum.Material.Neon);local stone=piece(m,"AttackStone",Vector3.new(1.5,1.5,1.5),CFrame.new(pos+Vector3.new(0,4,-2)),Color3.fromRGB(105,103,98),Enum.Material.Slate);stone.Shape=Enum.PartType.Ball;stone.Transparency=1;m.PrimaryPart=root;m:SetAttribute("BossMinion",true);m:SetAttribute("Floor",floor);m:SetAttribute("Alive",true);m:SetAttribute("Index",index);return m
end
local function spawn(self)local folder=self.Folder;for floor,y in ipairs(floors) do for i=1,5 do local a=math.rad((floor*67+i*61)%360);local pos=Vector3.new(math.cos(a)*68,y+1.5,math.sin(a)*68);make(folder,"BossMinion_F"..floor.."_"..i,pos,floor,i)end end end
local function nearest(pos)local best,bd=nil,math.huge;for _,plr in ipairs(Players:GetPlayers())do if plr:GetAttribute("RoundActive")==true and plr:GetAttribute("Eliminated")~=true then local ch=plr.Character;local root=ch and ch:FindFirstChild("HumanoidRootPart");local hum=ch and ch:FindFirstChildOfClass("Humanoid");if root and hum and hum.Health>0 then local d=(root.Position-pos).Magnitude;if d<bd then best,bd=plr,d end end end end;return best,bd end
local function attack(minion,target)
 local root=target.Character and target.Character:FindFirstChild("HumanoidRootPart");local head=minion:FindFirstChild("Head");local stone=minion:FindFirstChild("AttackStone");if not root or not head or not stone then return end;stone.Transparency=0;stone.CFrame=head.CFrame*CFrame.new(0,-1,-2);local hit=false;local conn;conn=stone.Touched:Connect(function(part)local char=part and part:FindFirstAncestorOfClass("Model");if char~=target.Character or hit then return end;hit=true;conn:Disconnect();stone.Transparency=1;local hum=char:FindFirstChildOfClass("Humanoid");if hum and hum.Health>0 then hum.Health=0 end;target:SetAttribute("Eliminated",true);fb(target,"MINION_HIT","💥 ПОМОЩНИК ПОПАЛ! ВОЗРОЖДЕНИЕ ЧЕРЕЗ 10 СЕКУНД");task.delay(10,function()if target.Parent and target:GetAttribute("RoundActive")==true then target:SetAttribute("Eliminated",false);target:LoadCharacter();fb(target,"MINION_RESPAWN","↻ ТЫ ВЕРНУЛСЯ В ИГРУ!")end end)end);TweenService:Create(stone,TweenInfo.new(.48,Enum.EasingStyle.Linear),{CFrame=CFrame.new(root.Position+Vector3.new(0,1,0))}):Play();task.delay(.7,function()if conn then conn:Disconnect()end;if stone.Parent then stone.Transparency=1 end end)
end
function Minions:Start(arena)self:Stop();self.Active=true;self.Arena=arena;self._token+=1;local token=self._token;local folder=Instance.new("Folder");folder.Name="BossMinions";folder.Parent=arena;self.Folder=folder;spawn(self);local r=ReplicatedStorage:FindFirstChild("Remotes");local f=r and r:FindFirstChild("Feedback");if f then f:FireAllClients("MINION_EVENT","👹 25 ПОМОЩНИКОВ БОССА ВЫШЛИ НА ВСЕ 5 ЭТАЖЕЙ!")end;task.spawn(function()while self.Active and token==self._token do task.wait(1.7);if not self.Active or token~=self._token then break end;for _,m in ipairs(folder:GetChildren())do if m:IsA("Model") and m:GetAttribute("Alive") then local root=m.PrimaryPart;local target,dist=root and nearest(root.Position);if target and dist<95 then attack(m,target)end end end end end);return true end
function Minions:Stop()self.Active=false;self._token+=1;if self.Folder then self.Folder:Destroy();self.Folder=nil end end
return Minions